### ISSUE TITLE
Crash on activity start

### ISSUE THREAD

**Issue by blacoste** [yaxim-org/yaxim#146]
Yaxim is no more working as it crashes on start. No other action required by the user. 
It is not solved by reinstalling app nor clearing app data.

Remark: I am a frequent user of the app.

Device : Nexus 5
Runtime environment: ART
App Version: 0.8.8 (was working with 0.8.7b)
Downloaded from F-Droid

ADB Logcat:
I/ActivityManager(  777): Start proc org.yaxim.androidclient for activity org.yaxim.androidclient/.MainWindow: pid=8068 uid=10114 gids={50114, 3003}
D/AndroidRuntime( 8068): Shutting down VM
E/AndroidRuntime( 8068): FATAL EXCEPTION: main
E/AndroidRuntime( 8068): Process: org.yaxim.androidclient, PID: 8068
E/AndroidRuntime( 8068): java.lang.NoClassDefFoundError: Failed resolution of: Lde/duenndns/ssl/MemorizingTrustManager;
E/AndroidRuntime( 8068):        at org.yaxim.androidclient.YaximApplication.onCreate(YaximApplication.java:29)
E/AndroidRuntime( 8068):        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime( 8068):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
E/AndroidRuntime( 8068):        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
E/AndroidRuntime( 8068):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
E/AndroidRuntime( 8068):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 8068):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 8068):        at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 8068):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8068):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 8068):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 8068): Caused by: java.lang.ClassNotFoundException: Didn't find class "de.duenndns.ssl.MemorizingTrustManager" on path: DexPathList[[zip file "/data/app/org.yaxim.androidclient-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.yaxim.androidclient-2, /vendor/lib, /system/lib]]
E/AndroidRuntime( 8068):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime( 8068):        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime( 8068):        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime( 8068):        ... 11 more
E/AndroidRuntime( 8068):        Suppressed: java.lang.ClassNotFoundException: de.duenndns.ssl.MemorizingTrustManager
E/AndroidRuntime( 8068):                at java.lang.Class.classForName(Native Method)
E/AndroidRuntime( 8068):                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime( 8068):                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime( 8068):                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime( 8068):                ... 12 more
E/AndroidRuntime( 8068):        Caused by: java.lang.NoClassDefFoundError: Class "Lde/duenndns/ssl/MemorizingTrustManager;" not found
E/AndroidRuntime( 8068):                ... 16 more
